### ISSUE TITLE
Update to latest spec

### ISSUE THREAD

**Issue by Keats** [graphql-rust/graphql-parser#15]
A new version of the spec was recently released: https://github.com/facebook/graphql/releases/tag/June2018

Looking at the list, at least block strings needs to be added. There is also the Type System Definition Language to go through to ensure the parser is working as expected from the spec.

**Comment by tailhook** [comment]
Block strings do work. Because we were implementing the latest draft.

It looks like typesystem definition language is what was called "Schema Definition Language" which is also supported since early days.

Another look at the spec would be nice to have, though. Since I've been implementing based on the draft.

**Comment by Keats** [comment]
Ah I should have checked if they were already implemented, sorry about that! I'll try to have a read through when I get some time

**Comment by LegNeato** [comment]
Going to close this. Please file specific issues for any missing functionality.
